### ISSUE TITLE
keepAliveTabs参数存储

### ISSUE THREAD

**Issue by TangDeYu** [dbfu/antd-pro-keepalive-tabs#1]
目前页面刷新keepAliveTabs参数就只为当前的路由，这里怎么存储下呢？
放缓存里面也是不行的 里面的children字段是不能存储的。
有什么好的方法进行缓存吗

**Comment by dbfu** [comment]
我们目前的解决方案是，用户刷新浏览器后，只保留那些页签，然后点页签的时候，判断children不存在了，然后去重新根据路由加载对应的组件。

**Comment by TangDeYu** [comment]
> 我们目前的解决方案是，用户刷新浏览器后，只保留那些页签，然后点页签的时候，判断children不存在了，然后去重新根据路由加载对应的组件。

我是想把children过滤掉在存储起来，但是重新获取对应组件渲染useOutlet的时候出了问题。

**Comment by dbfu** [comment]
> 

啥问题呢？

**Comment by TangDeYu** [comment]
> > 
> 
> 啥问题呢？

怎么通过path渲染出来对应的useOutlet组件呢

**Comment by dbfu** [comment]
> > > 
> > 
> > 
> > 啥问题呢？
> 
> 怎么通过path渲染出来对应的useOutlet组件呢

今晚回去帮你写个demo

**Comment by TangDeYu** [comment]
> 

我参考了你这个项目的多页签。

我自己处理的话应该就是这里需要修改 通过path 渲染。这个直接执行的话是只会走一次
<img width="600" alt="image" src="https://github.com/dbfu/antd-pro-keepalive-tabs/assets/52319042/5405290b-18c4-4846-9fc1-f427ab0c356f">

**Comment by dbfu** [comment]
> > 
> 
> 我参考了你这个项目的多页签。
> 
> 我自己处理的话应该就是这里需要修改 通过path 渲染。这个直接执行的话是只会走一次 <img alt="image" width="600" src="https://user-images.githubusercontent.com/52319042/239175152-5405290b-18c4-4846-9fc1-f427ab0c356f.png">

hooks不能在条件分支和遍历中使用的，你这个用法有问题。

**Comment by TangDeYu** [comment]
> > > 
> > 
> > 
> > 我参考了你这个项目的多页签。
> > 我自己处理的话应该就是这里需要修改 通过path 渲染。这个直接执行的话是只会走一次 <img alt="image" width="600" src="https://user-images.githubusercontent.com/52319042/239175152-5405290b-18c4-4846-9fc1-f427ab0c356f.png">
> 
> hooks不能在条件分支和遍历中使用的，你这个用法有问题。

是的 刚才写的有问题 layout.index 不用改动了。
我是在useKeepAliveTabs文件中 对existKeepAliveTab 的children字段判断 不存在直接插入下
<img width="718" alt="image" src="https://github.com/dbfu/antd-pro-keepalive-tabs/assets/52319042/7e9c63da-b7b1-4427-9bfa-b2ef68eaa17f">

**Comment by TangDeYu** [comment]
还有个地方想请教下。
useMatchRoute文件下的 根据useAppData 获取到所有的路由。但是这个获取到的是本地routes.js路由表的。不是从后端返回的路由数据。
我还在找文档是否有直接获取到服务端返回的 
<img width="308" alt="image" src="https://github.com/dbfu/antd-pro-keepalive-tabs/assets/52319042/851a0010-bf21-4552-b085-5bfcc948f183">
还是说 这里的  routes 直接换成后端返回的 在下面的逻辑重新读取下？

**Comment by dbfu** [comment]
> 还有个地方想请教下。 useMatchRoute文件下的 根据useAppData 获取到所有的路由。但是这个获取到的是本地routes.js路由表的。不是从后端返回的路由数据。 我还在找文档是否有直接获取到服务端返回的 <img alt="image" width="308" src="https://user-images.githubusercontent.com/52319042/239189867-851a0010-bf21-4552-b085-5bfcc948f183.png"> 还是说 这里的 routes 直接换成后端返回的 在下面的逻辑重新读取下？

可以把那个换成后端返回的路由数据，不过获取路由名称那里可能你需要自己处理一下。

**Comment by TangDeYu** [comment]
> > 还有个地方想请教下。 useMatchRoute文件下的 根据useAppData 获取到所有的路由。但是这个获取到的是本地routes.js路由表的。不是从后端返回的路由数据。 我还在找文档是否有直接获取到服务端返回的 <img alt="image" width="308" src="https://user-images.githubusercontent.com/52319042/239189867-851a0010-bf21-4552-b085-5bfcc948f183.png"> 还是说 这里的 routes 直接换成后端返回的 在下面的逻辑重新读取下？
> 
> 可以把那个换成后端返回的路由数据，不过获取路由名称那里可能你需要自己处理一下。

好的 谢谢~

**Comment by TangDeYu** [comment]
有个问题 提交到另一个issue了
